### ISSUE TITLE
Aaggregate multiple columns with a regular expression fails

### ISSUE THREAD

**Issue by cschubertcs** [GregorCH/ipet#49]
IPET-Version: 9b26c87
virtualenv-Version: 15.0.1
Evaluation file: [bug.xml.txt](https://github.com/GregorCH/ipet/files/1295798/bug.xml.txt) (github won't allow the xml extension)
Example out-file: [check.lookahead_bug_60.scip-lookahead-1.3-15s.linux.x86_64.gnu.opt.cpx.none.M620.ALAB.out.txt](https://github.com/GregorCH/ipet/files/1295809/check.lookahead_bug_60.scip-lookahead-1.3-15s.linux.x86_64.gnu.opt.cpx.none.M620.ALAB.out.txt)

Trying to aggregate multiple columns with a regular expression fails with the following error:

```
2017-09-12 13:46:14,399 - INFO - No external data file
2017-09-12 13:46:14,836 - WARNING - An error occurred for the column 'OtherCutoffs':
{'regex': 'BranchingRules_Cutoffs_.*', 'active': 'True', 'reduction': 'meanOrConcat', 'name': 'OtherCutoffs'}
Traceback (most recent call last):
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/indexes/base.py", line 1876, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4027)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3891)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12408)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12359)
KeyError: 'OtherCutoffs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3350, in set
    loc = self.items.get_loc(item)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/indexes/base.py", line 1878, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4027)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3891)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12408)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12359)
KeyError: 'OtherCutoffs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/bin/ipet-evaluate", line 4, in <module>
    __import__('pkg_resources').run_script('ipet==0.0.9', 'ipet-evaluate')
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/ipet-0.0.9-py3.5.egg/EGG-INFO/scripts/ipet-evaluate", line 205, in <module>
    theeval.evaluate(ExperimentManagement.getExperiment())
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/ipet-0.0.9-py3.5.egg/ipet/evaluation/IPETEvalTable.py", line 1394, in evaluate
    reduceddata = self.reduceToColumns(data, reduceddata)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/ipet-0.0.9-py3.5.egg/ipet/evaluation/IPETEvalTable.py", line 912, in reduceToColumns
    raise e
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/ipet-0.0.9-py3.5.egg/ipet/evaluation/IPETEvalTable.py", line 909, in reduceToColumns
    df_long, df_target = col.getColumnData(df_long, df_target, evalindexcols)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/ipet-0.0.9-py3.5.egg/ipet/evaluation/IPETEvalTable.py", line 506, in getColumnData
    df_long[self.getName()] = result
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2348, in __setitem__
    self._set_item(key, value)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/frame.py", line 2415, in _set_item
    NDFrame._set_item(self, key, value)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/generic.py", line 1459, in _set_item
    self._data.set(key, value)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3353, in set
    self.insert(len(self.items), item, value)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3454, in insert
    placement=slice(loc, loc + 1))
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/internals.py", line 2461, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/nfs/optimi/kombadon/bzfschuc/ipet/master-venv/lib/python3.5/site-packages/pandas/core/internals.py", line 84, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 13, placement implies 1
```

**Comment by GregorCH** [comment]
This nasty bug has not been covered by our regular tests, yet. The assignment 

`df_long[self.getName()] = result` 

expects one column on the left side, but receives 13 columns (all that match the regular expression). Previously, the method IPETEvaluationColumn.getColumnData() returned a result (one or several columns) for the parent column to work with, now it returns an entire data frame with multiple columns.

I think it is reasonable to force that **top level columns must not contain regular expressions** at all. Otherwise, this might have unforeseeable, uncotrollable side effects on the column order of the final evaluation frame.

What remains is the correct bundling of deeper columns when column data is recursively obtained. I fixed this by returning the children data along with the potentially modified data frames. A transformation column may use the returned data to apply its transformation function.
